# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='intent',
            name='sent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Sentence'),
        ),
        migrations.AddField(
            model_name='domain',
            name='sent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Sentence'),
        ),
    ]
