# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='intent',
            name='sent',
        ),
        migrations.AddField(
            model_name='sentence',
            name='domain',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='intent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Intent',
        ),
    ]
