# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20170727_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='slots',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
